export const videos = [
    {
        link: "https://www.youtube.com/watch?v=n2RNcPRtAiY",
        time: "14:20",
        thumbnail: "images/thumbnail-1.webp",
        channelPic: "images/channel-1.jpeg",
        channelLink: "https://www.youtube.com/c/mkbhd",
        channelName: "Marques Brownlee",
        subscribers: "15M subscribers",
        videoTitle: "Talking Tech and AI with Google CEO Sundar Pichai!",
        views: "3.4M",
        timeSinceReleased: "6 months Ago"
    },
    {
        link: "https://www.youtube.com/watch?v=mP0RAo9SKZk",
        time: "8:22",
        thumbnail: "images/thumbnail-2.webp",
        channelPic: "images/channel-2.jpeg",
        channelLink: "https://www.youtube.com/c/markiplier",
        channelName: "Markiplier",
        subscribers: "15M subscribers",
        videoTitle: "Try Not To Laugh Challenge #9!",
        views: "19M",
        timeSinceReleased: "4 years Ago"
    },
    {
        link: "https://www.youtube.com/watch?v=FgjPQQeTh1w",
        time: "9:13",
        thumbnail: "images/thumbnail-3.webp",
        channelPic: "images/channel-3.jpeg",
        channelLink: "https://www.youtube.com/user/SSSniperWolf",
        channelName: "SSSniperWolf",
        subscribers: "15M subscribers",
        videoTitle: "Crazy Tik Toks Taken Moments Before DISASTER",
        views: "12M",
        timeSinceReleased: "1 Year Ago"
    },
    {
        link: "https://www.youtube.com/watch?v=094y1Z2wpJg",
        time: "22:09",
        thumbnail: "images/thumbnail-4.webp",
        channelPic: "images/channel-4.jpeg",
        channelLink: "https://www.youtube.com/c/veritasium",
        channelName: "Veritasuim",
        subscribers: "15M subscribers",
        videoTitle: "The Simplest Math Problem No One Can Solve - Collatz Conjecture",
        views: "18M",
        timeSinceReleased: "4 months Ago"
    },
    {
        link: "https://www.youtube.com/watch?v=86CQq3pKSUw",
        time: "11:17",
        thumbnail: "images/thumbnail-5.webp",
        channelPic: "images/channel-5.jpeg",
        channelLink: "https://www.youtube.com/c/CSDojo",
        channelName: "CSDojo",
        subscribers: "15M subscribers",
        videoTitle: "Kadane's Algorithm to Maximum Sum Subarray Problem",
        views: "519K",
        timeSinceReleased: "5 years Ago"
    },
    {
        link: "https://www.youtube.com/watch?v=yXWw0_UfSFg",
        time: "19:59",
        thumbnail: "images/thumbnail-6.webp",
        channelPic: "images/channel-6.jpeg",
        channelLink: "https://www.youtube.com/channel/UCX6OQ3DkcsbYNE6H8uQQuVA",
        channelName:"MrBeast",
        subscribers: "15M subscribers",
        videoTitle: "Anything You Can Fit In The Circle I'll Pay For",
        views: "141M",
        timeSinceReleased: "1 years Ago"
    },
    {
        link: "https://www.youtube.com/watch?v=fNVa1qMbF9Y",
        time: "10:13",
        thumbnail: "images/thumbnail-7.webp",
        channelPic: "images/channel-7.jpeg",
        channelLink: "https://www.youtube.com/channel/UCP5tjEmvPItGyLhmjdwP7Ww",
        channelName: "RealLifeLore",
        subscribers: "15M subscribers",
        videoTitle: "Why Planes Don't Fly Over Tibet",
        views: "6.6M",
        timeSinceReleased: "1 year Ago"
    },
    {
        link: "https://www.youtube.com/watch?v=lFm4EM1juls",
        time: "7:12",
        thumbnail: "images/thumbnail-8.webp",
        channelPic: "images/channel-8.jpeg",
        channelLink: "https://www.youtube.com/channel/UCHAK6CyegY22Zj2GWrcaIxg",
        channelName: "Tech Vision",
        subscribers: "15M subscribers",
        videoTitle: "Inside The World's Biggest Passenger Plane",
        views: "3.7M",
        timeSinceReleased: "10 months Ago"
    },
    {
        link: "https://www.youtube.com/watch?v=ixmxOlcrlUc",
        time: "7:12",
        thumbnail: "images/thumbnail-9.webp",
        channelPic: "images/channel-9.jpeg",
        channelLink: "https://www.youtube.com/c/OFFICIALTHENXSTUDIOS",
        channelName: "ThenX",
        subscribers: "15M subscribers",
        videoTitle: "The SECRET to Super Human STRENGTH",
        views: "20M",
        timeSinceReleased: "3 years Ago"
    },
    {
        link: "https://www.youtube.com/watch?v=R2vXbFp5C9oY",
        time: "7:53",
        thumbnail: "images/thumbnail-10.webp",
        channelPic: "images/channel-10.jpeg",
        channelLink: "https://www.youtube.com/user/businessinsider",
        channelName: "Business Insider",
        subscribers: "15M subscribers",
        videoTitle: "How The World's Largest Cruise Ship Makes 30,000 Meals Every Day",
        views: "14M",
        timeSinceReleased: "1 year Ago"
    },
    {
        link: "https://www.youtube.com/watch?v=0nZuYyXET3s",
        time: "4:10",
        thumbnail: "images/thumbnail-11.webp",
        channelPic: "images/channel-11.jpeg",
        channelLink: "https://www.youtube.com/c/Destinationtips",
        channelName: "Destination Tips",
        subscribers: "15M subscribers",
        videoTitle: "Dubai's Crazy Underwater Train and Other Things #Only in Dubai",
        views: "3M",
        timeSinceReleased: "1 year Ago"
    },
    {
        link: "https://www.youtube.com/watch?v=9iMGFqMmUFs",
        time: "4:51",
        thumbnail: "images/thumbnail-12.webp",
        channelPic: "images/channel-12.jpeg",
        channelLink: "https://www.youtube.com/teded",
        channelName: "TED-Ed",
        subscribers: "15M subscribers",
        videoTitle: "What would happen if you didn't drink water? - Mia Nacamulli",
        views: "12M",
        timeSinceReleased: "5 years Ago"
    },
];